#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
H=0
while [ $H -lt 13 ]
do
    echo "Hour: $H"
    MIN=1
    while [ $MIN -lt 60 ]
    do
        echo $MIN
	let MIN+=1
    done
    let H+=1
done
